name: Bot Run

on:
  push:
    branches: [ main ]
    paths-ignore: "Readme.md"
  workflow_dispatch:

env:
  GitHubMail: "Storm@Shadow.com"
  GitHubName: "Not-Storm"
  Branch: "main"
  token: ${{ secrets.TOKEN}}
  nasakey: ${{ secrets.NASAKEY}}
  databaseUrl: ${{secrets.DATABASEURL}}
  databaseUsername: ${{secrets.DATABASEUSERNAME}}
  databasePassword: ${{secrets.DATABASEPASSWORD}}
  databaseName: ${{secrets.DATABASENAME}}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs and Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Installing Dependencies for main project
        run: |
          cd Evelin
          dotnet add package Discord.Addons.Hosting
          dotnet add package Discord.InteractivityAddon
          dotnet add package Discord.Net
          dotnet add package Discord.Net.Analyzers
          dotnet add package StyleCop.Analyzers
      
      - name: Installing Dependencies for database
        run: |
          cd Infrastructure
          dotnet add package Microsoft.EntityFrameworkCore -v 5.0.7
          dotnet add package StyleCop.Analyzers
          dotnet add package Npgsql -v 5.0.7
          dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL -v 5.0.7
          dotnet add package Microsoft.EntityFrameworkCore.Tools -v 5.0.7


      - name: Running DotNET
        timeout-minutes: 340
        continue-on-error: true
        run: |
          cd Evelin
          dotnet run Program.cs